name: CI (main)

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: setup rust toolchain
        run: rustup show
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@mdbook
      - name: check and build
        run: cargo x ci
      - uses: actions/upload-pages-artifact@v1
        with:
          path: mini-lsm-book/book

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
